ci:
  autofix_prs: false
  autoupdate_schedule: 'quarterly'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.0.1"
    hooks:
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/pycqa/flake8
    rev: "3.9.2"
    hooks:
      - id: flake8
  - repo: https://github.com/codespell-project/codespell
    rev: "v2.2.2"
    hooks:
    - id: codespell
      types_or: [python, markdown, rst]
      additional_dependencies: [tomli]
  - repo: https://github.com/aio-libs/sort-all
    rev: "v1.2.0"
    hooks:
      - id: sort-all
        types: [file, python]
