name: Build and upload to PyPI

# Only build on published releases
on:
  release:
    types:
      - published

jobs:
  build:
    name: Build sdist
    runs-on: ubuntu-18.04
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test-environment
          python-version: ${{ matrix.python-version }}
          channels: conda-forge/label/testing,conda-forge

      - name: Install dependencies
        run: |
          PACKAGES="cython fiona matplotlib-base numpy pyproj pykdtree scipy"
          PACKAGES="$PACKAGES owslib pep8 pillow pyshp pytest"
          PACKAGES="$PACKAGES pytest-xdist setuptools_scm shapely"
          conda install $PACKAGES

      - name: Create sdist
        run: python setup.py build_ext sdist

      - name: Save built packages as artifact
        uses: actions/upload-artifact@v3
        with:
          name: packages-${{ runner.os }}-${{ matrix.python-version }}
          path: dist/
          if-no-files-found: error
          retention-days: 5

  publish:
    name: Publish to PyPI
    needs: build
    environment:
      name: PyPI
      url: https://pypi.org/project/cartopy
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    runs-on: ubuntu-18.04

    steps:
      - name: Download packages
        uses: actions/download-artifact@v3

      - name: Consolidate packages for upload
        run: |
          mkdir dist
          cp packages-*/* dist/

      - name: Publish Package
        uses: pypa/gh-action-pypi-publish@v1.8.8
